config/routes.rb
Rails.application.routes.draw do

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  get 'errors/access_denied'

  get 'home/index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins, :controllers => { :admins => "admins" }
  devise_for :secretaries, :controllers => { :secretaries => "secretaries" }

  root 'home#index'
  get '/sistema' => 'home#sys'
  get '/prof' => 'home#index'
  get '/about' => 'home#about', as: :about
  get '/professors/sign_in/' => 'home#index'
  get "/users/sign_in/" => "home#index"

  resources :users, except: :edit

  resources :admins do
    collection do
      get :control_panel
      post :duplicate_students
      post :register_undergraduate_courses
      post :register_postgraduate_courses
    end
  end

  resources :advises
  post 'advises/:id/moveup' => 'advises#moveup', as: :moveup_advise
  post 'advises/:id/movedown' => 'advises#movedown', as: :movedown_advise

  resources :request_for_teaching_assistants, except: [:new]
  get 'request_for_teaching_assistants/:semester_id/new' => 'request_for_teaching_assistants#new', as: :new_request_for_teaching_assistant
  get 'request_for_teaching_assistants_for_semester/:semester_id/' => 'request_for_teaching_assistants#index_for_semester', as: :request_for_teaching_assistants_for_semester
  get 'request_for_teaching_assistants_for_professor/:professor_id/' => 'request_for_teaching_assistants#index_for_professor', as: :request_for_teaching_assistants_for_professor
  get 'request_for_teaching_assistants_for_professor_and_semester/:professor_id/:semester_id/' => 'request_for_teaching_assistants#index_for_professor', as: :request_for_teaching_assistants_for_professor_and_semester

  resources :professors
  get 'professors/:id/change_password' => 'professors#change_password', as: :change_professor_password
  post 'professors/:id/make_superprofessor' => 'professors#make_superprofessor', as: :make_super_professor

  resources :courses

  resources :secretaries
  get 'secretaries/:id/change_password' => 'secretaries#change_password', as: :change_secretary_password

  resources :students, except: :show

  resources :assistant_frequency do
    collection do
      get :index
      post :request_frequency
    end
  end

  get 'dumps/' => 'dumps#index', as: :dumps

  get 'assistant_frequency/monthly_control/:semester_id/:month/:filter' => 'assistant_frequency#monthly_control', as: :assistant_frequency_monthly_control
  get 'assistant_frequency/monthly_control/:semester_id/:month/:department_id/:filter' => 'assistant_frequency#monthly_control', as: :assistant_frequency_monthly_control_for_department
  get 'assistant_frequency/:id/edit_comment' => 'assistant_frequency#edit_comment', as: :edit_assistant_frequency_comment
  post 'assistant_frequency/open_period/:semester_id/:month/:last_filter' => 'assistant_frequency#open_frequency_period', as: :open_frequency_period
  post 'assistant_frequency/close_period/:semester_id/:month/:last_filter' => 'assistant_frequency#close_frequency_period', as: :close_frequency_period
  post 'assistant_frequency/request_frequency/' => 'assistant_frequency#request_frequency', as: :request_frequency
  post 'assistant_frequency/mark_generic_assistant_role_frequency/' => 'assistant_frequency#mark_generic_assistant_role_frequency', as: :mark_generic_assistant_role_frequency
  post 'assistant_frequency/mark_assistant_role_frequency/' => 'assistant_frequency#mark_assistant_role_frequency', as: :mark_assistant_role_frequency
  post 'assistant_frequency/:id/comment' => 'assistant_frequency#update_comment', as: :update_assistant_frequency_comment
  post 'assistant_frequency/pay_all_assistants/:semester_id/:month' => 'assistant_frequency#pay_all_assistants', as: :pay_all_assistants

  resources :semesters
  get 'semesters/:id/edit_date' => 'semesters#edit_date', as: :semester_edit_date
  post 'semesters/:id/open' => 'semesters#open', as: :open_semester
  post 'semesters/:id/activate' => 'semesters#activate', as: :activate_semester
  post 'semesters/:id/close' => 'semesters#close', as: :close_semester
  post 'semesters/:id/deactivate' => 'semesters#deactivate', as: :deactivate_semester
  post 'semesters/:id/open_evaluation_period' => 'semesters#open_evaluation_period', as: :open_semester_evaluation_period
  post 'semesters/:id/close_evaluation_period' => 'semesters#close_evaluation_period', as: :close_semester_evaluation_period
  patch 'semesters/:id/update_date' => 'semesters#update_date', as: :semester_update_date

  resources :candidatures, except: :new
  get 'candidatures/:id/download_transcript' => 'candidatures#download_transcript', as: :download_candidature_transcript
  get 'candidatures/:semester_id/new' => 'candidatures#new', as: :new_candidature
  get 'candidatures/list/:department_id/' => 'candidatures#index', as: :candidatures_with_department
  get 'candidatures/for_department/:semester_id/:department_id/' => 'candidatures#index_for_department', as: :candidatures_for_department
  get 'candidatures/for_student/:student_id/' => 'candidatures#index_for_student', as: :candidatures_for_student

  get 'assistant_roles/' => 'assistant_roles#index', as: :assistant_roles
  get 'assistant_roles/edit_date/:id' => 'assistant_roles#edit_date', as: :assistant_roles_edit_date
  get 'assistant_roles/for_semester/:semester_id' => 'assistant_roles#index', as: :assistant_roles_for_semester
  get 'assistant_roles/for_semester/:semester_id/:department_id' => 'assistant_roles#index', as: :assistant_roles_for_semester_and_department
  get 'assistant_roles/for_professor/:professor_id/' => 'assistant_roles#index_for_professor', as: :assistant_roles_for_professor
  get 'assistant_roles/for_professor/:professor_id/:semester_id' => 'assistant_roles#index_for_professor', as: :assistant_roles_for_professor_and_semester
  get 'assistant_roles/certificate/:id' => 'assistant_roles#certificate', as: :certificate
  get 'assistant_roles/report_form/:id' => 'assistant_roles#report_form', as: :report_form
  get 'assistant_roles/print_report/:id' => 'assistant_roles#print_report', as: :print_report
  get 'assistant_roles/:request_for_teaching_assistant_id/new' => 'assistant_roles#new', as: :new_assistant_role
  post 'assistant_roles/notify_for_semester/:semester_id' => 'assistant_roles#notify_for_semester', as: :notify_assistant_roles_for_semester
  post 'assistant_roles/request_evaluations_for_semester/:semester_id' => 'assistant_roles#request_evaluations_for_semester', as: :request_assistant_evaluations_for_semester
  post 'assistant_roles/:request_for_teaching_assistant_id/:student_id/create' => 'assistant_roles#create', as: :create_assistant_role
  post 'assistant_roles/deactivate_assistant_role/:id' => 'assistant_roles#deactivate_assistant_role', as: :deactivate_assistant_role
  post 'assistant_roles/reactivate_assistant_role/:id' => 'assistant_roles#reactivate_assistant_role', as: :reactivate_assistant_role
  patch 'assistant_roles/update_date/:id' => 'assistant_roles#update_date', as: :update_assistant_role_date
  patch 'assistant_roles/:id/' => 'assistant_roles#update', as: :update_assistant_role
  patch 'assistant_roles/make_definitive/:id' => 'assistant_roles#make_definitive', as: :make_assistant_role_definitive
  delete 'assistant_roles/:id/' => 'assistant_roles#destroy', as: :destroy_assistant_role

  resources :assistant_evaluations, except: [:index, :show, :new, :destroy]
  get 'assistant_evaluations/for_student/:student_id/' => 'assistant_evaluations#index_for_student', as: :assistant_evaluations_for_student
  get 'assistant_evaluations/:assistant_role_id/new' => 'assistant_evaluations#new', as: :new_assistant_evaluation

  get "help_students/:id" => "help_students#index", :as => :help_students

  get "help_professors/:id" => "help_professors#index", :as => :help_professors

  match '/403', to: 'errors#access_denied', via: :all
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  devise_scope :user do
    match '/users/auth/USP/callback', to: 'users/omniauth_callbacks#usp', via: [:get, :post]
  end

  get '/_instructions' => redirect('http://www.ime.usp.br/grad/monitoria'), as: :official_instructions

end

app/models/assistant_frequency.rb
class AssistantFrequency < ActiveRecord::Base
  include ActiveModel::Validations
  validates :assistant_role_id, presence: true
  validates :month, presence: true, inclusion: {in: 1..12}
  belongs_to :assistant_role

  def semester
  	assistant_role.semester
  end

  def professor
    assistant_role.professor
  end

  def pay_if_present
    if presence == true and payment != true
      update_column(:payment, true)
    end
  end

  def self.FILTER_ALL
    0
  end

  def self.FILTER_PENDING
    1
  end

  def self.FILTER_PRESENT
    2
  end

  def self.FILTER_ABSENT
    3
  end

  def self.FILTER_PAID
    4
  end

  def self.FILTERS
    ["Todo", "Pendente", "Presente", "Ausente", "Pago"]
  end

  def self.current_frequencies
    AssistantFrequency.where assistant_role: (AssistantRole.for_semester Semester.current)
  end

  def self.schedule_notifications period
    month = Semester.current.months[period]
    Delayed::Job.enqueue(FrequencyMailJob.new, priority: 0, run_at: DateTime.new(Time.now.year, month, 20, 8, 0, 0).getutc)
    Delayed::Job.enqueue(FrequencyReminderJob.new, priority: 0, run_at: DateTime.new(Time.now.year, month, 26, 8, 0, 0).getutc)
    Delayed::Job.enqueue(LastFrequencyReminderJob.new, priority: 0, run_at: DateTime.new(Time.now.year, month, 30, 8, 0, 0).getutc)
    Delayed::Job.enqueue(CloseFrequencyPeriodJob.new(period), priority: 0, run_at: DateTime.new(Time.now.year, month+1, 2, 8, 0, 0).getutc)
    # NOTE: February is never included as for frequency, so there will always be a 30th day of the current onth
  end

  def self.notify_frequency
    # FIXME: use period instead of month
    month = Time.now.month
    professors = {}
    Semester.current.open_frequency_month month
    AssistantRole.all_current.each do |role|
      professors[role.professor] = [] unless professors.key? role.professor
      professors[role.professor].push role
    end
    professors.each do |professor, roles|
      wait
      NotificationMailer.frequency_request_notification(professor, roles).deliver
    end
    if (month != 6 && month != 11)
      schedule_notifications Semester.month_to_period(month + 1)
    else
      AssistantEvaluation.request_evaluations_for_semester Semester.current
    end
  end

  def self.notify_frequency_reminder
    professors = {}
    students = {}
    AssistantRole.pending_for_month(Time.now.month).each do |role|
      professors[role.professor] = [] unless professors.key? role.professor
      professors[role.professor].push role
      students[role.student] = [] unless students.key? role.student
      students[role.student].push role
    end
    professors.each do |professor, roles|
      wait
      NotificationMailer.frequency_request_notification(professor, roles).deliver
    end
    students.each do |student, roles|
      wait
      NotificationMailer.pending_frequencies_notification(student, roles).deliver
    end
  end

  def self.notify_last_frequency_reminder
    notify_frequency_reminder
    Professor.where(:professor_rank => [1, 2]).each do |super_professor|
      pending_roles = []
      AssistantRole.pending_for_month(Time.now.month).each do |role|
        if role.course.department == super_professor.department
            pending_roles.push(role)
        end
      end
      if pending_roles.any?
        wait
        NotificationMailer.last_pending_frequencies_notification(pending_roles, super_professor).deliver
      end
    end
  end

  def self.for_semester_and_month semester, month
    requests_for_semester = RequestForTeachingAssistant.where(semester: semester)
    roles_for_semester = AssistantRole.where(request_for_teaching_assistant: requests_for_semester)
    where(assistant_role: roles_for_semester, month: month)
  end

  private

  def self.wait
    if Rails.env.production?
      sleep(120.0)
    end
  end

end

app/controllers/assistant_frequency_controller.rb
class AssistantFrequencyController < ApplicationController

  authorize_resource

  def monthly_control
    @semester = Semester.find params[:semester_id]
    @month = params[:month].to_i
    @filter = params[:filter].to_i
    if current_hiper_professor? or secretary_signed_in?
      if params[:department_id].present?
        @department = Department.find params[:department_id]
        @assistant_roles = AssistantRole.for_department_and_semester @department, @semester
      else
        @assistant_roles = AssistantRole.for_semester @semester
      end
      if @filter != AssistantFrequency.FILTER_ALL
        @assistant_roles = @assistant_roles.map { |x| x }.keep_if do |role|
          (role.frequency_status_for_month @month) == AssistantFrequency.FILTERS[@filter]
        end
      end
    else
      @assistant_roles = AssistantRole.for_semester @semester
      @assistant_roles = @assistant_roles.map { |x| x }.keep_if do |role|
        @current_user.should_see_role role
      end
    end
  end

  def open_frequency_period
    @semester = Semester.find params[:semester_id]
    @month = params[:month].to_i
    @filter = params[:last_filter].to_i
    @semester.open_frequency_period(Semester.month_to_period @month)
    redirect_to assistant_frequency_monthly_control_path(@semester, @month, @filter)
  end

  def close_frequency_period
    @semester = Semester.find params[:semester_id]
    @month = params[:month].to_i
    @filter = params[:last_filter].to_i
    @semester.close_frequency_period(Semester.month_to_period @month)
    redirect_to assistant_frequency_monthly_control_path(@semester, @month, @filter)
  end

  def mark_assistant_role_frequency
    presence = params[:presence]
    month = params[:month]
    role = params[:role]
    id = params[:pid]
    @assistant_frequency = AssistantFrequency.new(month: month, presence: presence, assistant_role_id: role, payment: false, comment: "")
    if @assistant_frequency.save
      if presence
        respond_to do |format|
          format.html { redirect_to assistant_roles_for_professor_path(id), notice: 'Presença marcada com sucesso.' }
        end
      else
        respond_to do |format|
          format.html { redirect_to assistant_roles_for_professor_path(id), notice: 'Ausência marcada com sucesso.' }
        end
      end
    else
        respond_to do |format|
          format.html { redirect_to assistant_roles_for_professor_path(id), notice: 'Erro ao marcar frequência.' }
        end
    end
  end

  def mark_generic_assistant_role_frequency
    presence = params[:presence]
    month = params[:month]
    role = params[:role]
    id = params[:pid]
    @assistant_frequency = AssistantFrequency.new(month: month, presence: presence, assistant_role_id: role, payment: false)
    if @assistant_frequency.save
      if presence
        respond_to do |format|
          format.html { redirect_to assistant_frequency_monthly_control_path(@assistant_frequency.semester, month, AssistantFrequency.FILTER_ALL), notice: 'Presença marcada com sucesso.' }
        end
      else
        respond_to do |format|
          format.html { redirect_to assistant_frequency_monthly_control_path(@assistant_frequency.semester, month, AssistantFrequency.FILTER_ALL), notice: 'Ausência marcada com sucesso.' }
        end
      end
    else
        respond_to do |format|
          format.html { redirect_to assistant_frequency_monthly_control_path(@assistant_frequency.semester, month, AssistantFrequency.FILTER_ALL), notice: 'Erro ao marcar frequência.' }
        end
    end
  end

  # GET /assistant_frequency/1/edit_comment
  def edit_comment
    @frequency = AssistantFrequency.find assistant_frequency_params[:id]
  rescue ActiveRecord::RecordNotFound
    raise ActionController::RoutingError.new('Not Found')
  end

  # POST /assistant_frequency/1/comment
  def update_comment
    @frequency = AssistantFrequency.find (assistant_frequency_params[:id])
    @frequency.update(comment: assistant_frequency_params[:comment])
    respond_to do |format|
      format.html { redirect_to assistant_roles_for_professor_path(@frequency.professor, @frequency.semester), notice: 'Observação realizada com sucesso.' }
    end
  rescue ActiveRecord::RecordNotFound
    raise ActionController::RoutingError.new('Not Found')
  end

  def pay_all_assistants
    semester = Semester.find params[:semester_id]
    month = params[:month]
    AssistantFrequency.for_semester_and_month(semester, month).each do |freq|
      freq.pay_if_present
    end
    redirect_to assistant_frequency_monthly_control_path(semester, month, AssistantFrequency.FILTER_ALL)
  end

  private

  def assistant_frequency_params
    params.permit(:id, :comment)
  end

end

app/helpers/assistant_frequency_helper.rb
module AssistantFrequencyHelper
end

app/views/assistant_frequency/edit_comment.html.erb
<h1>Meus monitores</h1>

<ul class="list-group">
  <li class="list-group-item">
    <strong>Monitor(a):</strong> <%= @frequency.assistant_role.student.name %>
  </li>
  <li class="list-group-item">
    <strong>Disciplina:</strong> <%= @frequency.assistant_role.course.full_name %>
  </li>
  <li class="list-group-item">
    <strong>Período:</strong> <%= month_name(@frequency.month) %>, <%= @frequency.semester.as_s %>
  </li>
</ul>

<p>
  Escreva abaixo quaisquer observações a respeito da presença deste(a) monitor(a) na disciplina e mês indicados. Este campo não é obrigatório.
</p>

<%= form_tag(update_assistant_frequency_comment_path(@frequency), method: :post) do %>
  <p><%= text_area_tag :comment, @frequency.comment %></p>
  <%= submit_tag("Finalizar") %>
<% end %>

app/views/assistant_frequency/monthly_control.html.erb
<h1>Controle de frequência</h1>

<div class="row" style="height:1em;"></div>

<div class="row">
</div>

<div class="row">
  <div class="col-sm-3">
    <div class="dropdown">
      <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
        <%= @semester.as_s %>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <% Semester.all.reverse.each do |semester| %>
          <li><%= link_to semester.as_s, assistant_frequency_monthly_control_path(semester, @month, @filter)%></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% if current_hiper_professor? or secretary_signed_in? %>
    <div class="col-sm-3">
      <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
          <% if @department.nil? %>
            Todos
          <% else %>
            <%= @department.code %>
          <% end %>
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li>
            <%= link_to "Todos", assistant_frequency_monthly_control_path(@semester, @month, @filter) %>
          </li>
          <% Department.all.each do |department| %>
            <li><%= link_to department.code, assistant_frequency_monthly_control_for_department_path(@semester, @month, department, @filter)%></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% else %>
    <div class="col-sm-6"></div>
  <% end %>
  <% if secretary_signed_in? and @semester.active %>
    <div class="col-sm-2">
      <%= button_link_to "Pagar monitores" , pay_all_assistants_path(@semester, @month), method: :post %>
    </div>
    <div class="col-sm-2">
      <% if @semester.frequency_open?(Semester.month_to_period @month) %>
        <%= button_link_to "Fechar período de frequência" , close_frequency_period_path(@semester, @month, @filter), method: :post %>
      <% else %>
        <%= button_link_to "Abrir período de frequência" , open_frequency_period_path(@semester, @month, @filter), method: :post %>
      <% end %>
    </div>
  <% end %>
</div>

<div class="row" style="height:1em;"></div>

<div class="row text-center">
  <ul class="pagination">
    <% for filter in 0..4 do %>
      <% if filter == @filter %>
        <li class="active"><a href="#"><%= AssistantFrequency.FILTERS[filter] %>s</a></li>
      <% elsif @department.nil? %>
        <li><%= link_to AssistantFrequency.FILTERS[filter]+"s", assistant_frequency_monthly_control_path(@semester, @month, filter)%></li>
      <% else %>
        <li><%= link_to AssistantFrequency.FILTERS[filter]+"s", assistant_frequency_monthly_control_for_department_path(@semester, @month, @department, filter)%></li>
      <% end %>
    <% end %>
  </ul>
</div>

<div class="row" style="height:1em;"></div>

<ul class="nav nav-tabs">
  <% for i in 0..3 do %>
    <% if i == Semester.month_to_period(@month) %>
      <li class="active"><a><%= month_name(@month) %></a></li>
    <% elsif @department.nil? %>
      <li><%= link_to month_name(@semester.months[i]), assistant_frequency_monthly_control_path(@semester, @semester.months[i], @filter) %></li>
    <% else %>
      <li><%= link_to month_name(@semester.months[i]), assistant_frequency_monthly_control_for_department_path(@semester, @semester.months[i],@department, @filter) %></li>
    <% end %>
  <% end %>
</ul>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Monitor(a)</th>
      <th>Disciplina</th>
      <th>Professor(a)</th>
      <th>Presença</th>
    </tr>
  </thead>
  <tbody>
    <% @assistant_roles.each do |role| %>
      <tr>
        <td><%= role.student.name %></td>
        <td><%= role.request_for_teaching_assistant.course.course_code %></td>
        <td><%= role.request_for_teaching_assistant.professor.name %></td>
        <td>
          <% if role.active %>
            <% status = role.frequency_status_for_month(@month) %>
            <% if secretary_signed_in? %>
              <% css = "text-center" %>
              <% if status == "Pendente" then css += " text-danger" end %>
              <p class="<%= css %>">
                <%= status %>
                <% percentage = role.month_presence @month %>
                <% if status == "Presente" and not percentage.nil? %>
                  (<%= "#{'%.2f' % percentage}" %>%)
                <% end %>
              </p>
            <% else # assume professor because of cancan %>
              <% if status == "Pendente" and role.semester.frequency_open? Semester.month_to_period(@month) %>
                <div class="col-sm-12 col-lg-6 text-center">
                  <%= button_to "Presente", { controller: "assistant_frequency", action: "mark_generic_assistant_role_frequency", role: role.id, month: @month, presence: true, pid: role.professor.id}, method: :post, class: "btn btn-primary btn-xs", data: { confirm: 'Deseja mesmo marcar presença para este monitor?' } %>
                </div>
                <div class="col-sm-12 col-lg-6 text-center">
                  <%= button_to "Ausente", { controller: "assistant_frequency", action: "mark_generic_assistant_role_frequency", role: role.id, month: @month, presence: false, pid: role.professor.id}, method: :post, class: "btn btn-primary btn-xs", data: { confirm: 'Deseja mesmo marcar ausência para este monitor?' }  %>
                </div>
              <% else %>
                <%= content_tag :span, class: "text-center" do -%>
                  <%= status %>
                <% end %>
              <% end %>
            <% end %>
          <% else %>
            Desativado
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>