config/routes.rb
Rails.application.routes.draw do

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  get 'errors/access_denied'

  get 'home/index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins, :controllers => { :admins => "admins" }
  devise_for :secretaries, :controllers => { :secretaries => "secretaries" }

  root 'home#index'
  get '/sistema' => 'home#sys'
  get '/prof' => 'home#index'
  get '/about' => 'home#about', as: :about
  get '/professors/sign_in/' => 'home#index'
  get "/users/sign_in/" => "home#index"

  resources :users, except: :edit

  resources :admins do
    collection do
      get :control_panel
      post :duplicate_students
      post :register_undergraduate_courses
      post :register_postgraduate_courses
    end
  end

  resources :advises
  post 'advises/:id/moveup' => 'advises#moveup', as: :moveup_advise
  post 'advises/:id/movedown' => 'advises#movedown', as: :movedown_advise

  resources :request_for_teaching_assistants, except: [:new]
  get 'request_for_teaching_assistants/:semester_id/new' => 'request_for_teaching_assistants#new', as: :new_request_for_teaching_assistant
  get 'request_for_teaching_assistants_for_semester/:semester_id/' => 'request_for_teaching_assistants#index_for_semester', as: :request_for_teaching_assistants_for_semester
  get 'request_for_teaching_assistants_for_professor/:professor_id/' => 'request_for_teaching_assistants#index_for_professor', as: :request_for_teaching_assistants_for_professor
  get 'request_for_teaching_assistants_for_professor_and_semester/:professor_id/:semester_id/' => 'request_for_teaching_assistants#index_for_professor', as: :request_for_teaching_assistants_for_professor_and_semester

  resources :professors
  get 'professors/:id/change_password' => 'professors#change_password', as: :change_professor_password
  post 'professors/:id/make_superprofessor' => 'professors#make_superprofessor', as: :make_super_professor

  resources :courses

  resources :secretaries
  get 'secretaries/:id/change_password' => 'secretaries#change_password', as: :change_secretary_password

  resources :students, except: :show

  resources :assistant_frequency do
    collection do
      get :index
      post :request_frequency
    end
  end

  get 'dumps/' => 'dumps#index', as: :dumps

  get 'assistant_frequency/monthly_control/:semester_id/:month/:filter' => 'assistant_frequency#monthly_control', as: :assistant_frequency_monthly_control
  get 'assistant_frequency/monthly_control/:semester_id/:month/:department_id/:filter' => 'assistant_frequency#monthly_control', as: :assistant_frequency_monthly_control_for_department
  get 'assistant_frequency/:id/edit_comment' => 'assistant_frequency#edit_comment', as: :edit_assistant_frequency_comment
  post 'assistant_frequency/open_period/:semester_id/:month/:last_filter' => 'assistant_frequency#open_frequency_period', as: :open_frequency_period
  post 'assistant_frequency/close_period/:semester_id/:month/:last_filter' => 'assistant_frequency#close_frequency_period', as: :close_frequency_period
  post 'assistant_frequency/request_frequency/' => 'assistant_frequency#request_frequency', as: :request_frequency
  post 'assistant_frequency/mark_generic_assistant_role_frequency/' => 'assistant_frequency#mark_generic_assistant_role_frequency', as: :mark_generic_assistant_role_frequency
  post 'assistant_frequency/mark_assistant_role_frequency/' => 'assistant_frequency#mark_assistant_role_frequency', as: :mark_assistant_role_frequency
  post 'assistant_frequency/:id/comment' => 'assistant_frequency#update_comment', as: :update_assistant_frequency_comment
  post 'assistant_frequency/pay_all_assistants/:semester_id/:month' => 'assistant_frequency#pay_all_assistants', as: :pay_all_assistants

  resources :semesters
  get 'semesters/:id/edit_date' => 'semesters#edit_date', as: :semester_edit_date
  post 'semesters/:id/open' => 'semesters#open', as: :open_semester
  post 'semesters/:id/activate' => 'semesters#activate', as: :activate_semester
  post 'semesters/:id/close' => 'semesters#close', as: :close_semester
  post 'semesters/:id/deactivate' => 'semesters#deactivate', as: :deactivate_semester
  post 'semesters/:id/open_evaluation_period' => 'semesters#open_evaluation_period', as: :open_semester_evaluation_period
  post 'semesters/:id/close_evaluation_period' => 'semesters#close_evaluation_period', as: :close_semester_evaluation_period
  patch 'semesters/:id/update_date' => 'semesters#update_date', as: :semester_update_date

  resources :candidatures, except: :new
  get 'candidatures/:id/download_transcript' => 'candidatures#download_transcript', as: :download_candidature_transcript
  get 'candidatures/:semester_id/new' => 'candidatures#new', as: :new_candidature
  get 'candidatures/list/:department_id/' => 'candidatures#index', as: :candidatures_with_department
  get 'candidatures/for_department/:semester_id/:department_id/' => 'candidatures#index_for_department', as: :candidatures_for_department
  get 'candidatures/for_student/:student_id/' => 'candidatures#index_for_student', as: :candidatures_for_student

  get 'assistant_roles/' => 'assistant_roles#index', as: :assistant_roles
  get 'assistant_roles/edit_date/:id' => 'assistant_roles#edit_date', as: :assistant_roles_edit_date
  get 'assistant_roles/for_semester/:semester_id' => 'assistant_roles#index', as: :assistant_roles_for_semester
  get 'assistant_roles/for_semester/:semester_id/:department_id' => 'assistant_roles#index', as: :assistant_roles_for_semester_and_department
  get 'assistant_roles/for_professor/:professor_id/' => 'assistant_roles#index_for_professor', as: :assistant_roles_for_professor
  get 'assistant_roles/for_professor/:professor_id/:semester_id' => 'assistant_roles#index_for_professor', as: :assistant_roles_for_professor_and_semester
  get 'assistant_roles/certificate/:id' => 'assistant_roles#certificate', as: :certificate
  get 'assistant_roles/report_form/:id' => 'assistant_roles#report_form', as: :report_form
  get 'assistant_roles/print_report/:id' => 'assistant_roles#print_report', as: :print_report
  get 'assistant_roles/:request_for_teaching_assistant_id/new' => 'assistant_roles#new', as: :new_assistant_role
  post 'assistant_roles/notify_for_semester/:semester_id' => 'assistant_roles#notify_for_semester', as: :notify_assistant_roles_for_semester
  post 'assistant_roles/request_evaluations_for_semester/:semester_id' => 'assistant_roles#request_evaluations_for_semester', as: :request_assistant_evaluations_for_semester
  post 'assistant_roles/:request_for_teaching_assistant_id/:student_id/create' => 'assistant_roles#create', as: :create_assistant_role
  post 'assistant_roles/deactivate_assistant_role/:id' => 'assistant_roles#deactivate_assistant_role', as: :deactivate_assistant_role
  post 'assistant_roles/reactivate_assistant_role/:id' => 'assistant_roles#reactivate_assistant_role', as: :reactivate_assistant_role
  patch 'assistant_roles/update_date/:id' => 'assistant_roles#update_date', as: :update_assistant_role_date
  patch 'assistant_roles/:id/' => 'assistant_roles#update', as: :update_assistant_role
  patch 'assistant_roles/make_definitive/:id' => 'assistant_roles#make_definitive', as: :make_assistant_role_definitive
  delete 'assistant_roles/:id/' => 'assistant_roles#destroy', as: :destroy_assistant_role

  resources :assistant_evaluations, except: [:index, :show, :new, :destroy]
  get 'assistant_evaluations/for_student/:student_id/' => 'assistant_evaluations#index_for_student', as: :assistant_evaluations_for_student
  get 'assistant_evaluations/:assistant_role_id/new' => 'assistant_evaluations#new', as: :new_assistant_evaluation

  get "help_students/:id" => "help_students#index", :as => :help_students

  get "help_professors/:id" => "help_professors#index", :as => :help_professors

  match '/403', to: 'errors#access_denied', via: :all
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  devise_scope :user do
    match '/users/auth/USP/callback', to: 'users/omniauth_callbacks#usp', via: [:get, :post]
  end

  get '/_instructions' => redirect('http://www.ime.usp.br/grad/monitoria'), as: :official_instructions

end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "erro impediu", "erros impediram") %> esse admin de ser salvo:</h3>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :email, t('activerecord.attributes.admin.email') %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, t('activerecord.attributes.admin.password') %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, t('activerecord.attributes.admin.password_confirmation') %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.submit "Enviar" %>
  </div>
<% end %>

app/views/admins/control_panel.html.erb
<h1>Administração do sistema</h1>

<%= button_link_to "Disciplinas", courses_path %>
<%= button_link_to "Professores", professors_path %>
<%= button_link_to "Funcionários", secretaries_path %>
<%= button_link_to "Alunos", students_path %>

<div>
  <h3>Cadastro de disciplinas oferecidas no semestre</h3>
  <%= button_to "Cadastrar disciplinas de graduação", {controller: "admins", :action => "register_undergraduate_courses", :method => 'post'}, {class:"btn btn-primary"} %>
  <br>
  <%= button_to "Cadastrar disciplinas de pós-graduação", {controller: "admins", :action => "register_postgraduate_courses", :method => 'post'}, {class:"btn btn-primary"} %>
  <br>
  <%= button_to "Detectar alunos duplicados", {controller: "admins", :action => "duplicate_students", :method => 'get'}, {class:"btn btn-primary"} %>
</div>

<% if @duplicates then %>
  <div>
    <h3>Alunos com número USP duplicados:</h3>
    <% @duplicates.each do |entry| %>
      <p>
        <%= entry[0].nusp %>:
        <% entry.each_with_index do |student, i| %>
          <%= button_link_to i.to_s, student %>
        <% end %>
      </p>
    <% end %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Edição do Admin</h1>

<%= render 'form' %>

app/views/admins/show.html.erb
<p>
  <strong><%= t('activerecord.attributes.admin.email') + ':' %></strong>
  <%= @admin.email %>
</p>
<% if admin_signed_in? %>
  <p>
      <%= button_link_to 'Editar', edit_admin_path(@admin) %>
  </p>
<% end %>