config/routes.rb
Rails.application.routes.draw do

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  get 'errors/access_denied'

  get 'home/index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins, :controllers => { :admins => "admins" }
  devise_for :secretaries, :controllers => { :secretaries => "secretaries" }

  root 'home#index'
  get '/sistema' => 'home#sys'
  get '/prof' => 'home#index'
  get '/about' => 'home#about', as: :about
  get '/professors/sign_in/' => 'home#index'
  get "/users/sign_in/" => "home#index"

  resources :users, except: :edit

  resources :admins do
    collection do
      get :control_panel
      post :duplicate_students
      post :register_undergraduate_courses
      post :register_postgraduate_courses
    end
  end

  resources :advises
  post 'advises/:id/moveup' => 'advises#moveup', as: :moveup_advise
  post 'advises/:id/movedown' => 'advises#movedown', as: :movedown_advise

  resources :request_for_teaching_assistants, except: [:new]
  get 'request_for_teaching_assistants/:semester_id/new' => 'request_for_teaching_assistants#new', as: :new_request_for_teaching_assistant
  get 'request_for_teaching_assistants_for_semester/:semester_id/' => 'request_for_teaching_assistants#index_for_semester', as: :request_for_teaching_assistants_for_semester
  get 'request_for_teaching_assistants_for_professor/:professor_id/' => 'request_for_teaching_assistants#index_for_professor', as: :request_for_teaching_assistants_for_professor
  get 'request_for_teaching_assistants_for_professor_and_semester/:professor_id/:semester_id/' => 'request_for_teaching_assistants#index_for_professor', as: :request_for_teaching_assistants_for_professor_and_semester

  resources :professors
  get 'professors/:id/change_password' => 'professors#change_password', as: :change_professor_password
  post 'professors/:id/make_superprofessor' => 'professors#make_superprofessor', as: :make_super_professor

  resources :courses

  resources :secretaries
  get 'secretaries/:id/change_password' => 'secretaries#change_password', as: :change_secretary_password

  resources :students, except: :show

  resources :assistant_frequency do
    collection do
      get :index
      post :request_frequency
    end
  end

  get 'dumps/' => 'dumps#index', as: :dumps

  get 'assistant_frequency/monthly_control/:semester_id/:month/:filter' => 'assistant_frequency#monthly_control', as: :assistant_frequency_monthly_control
  get 'assistant_frequency/monthly_control/:semester_id/:month/:department_id/:filter' => 'assistant_frequency#monthly_control', as: :assistant_frequency_monthly_control_for_department
  get 'assistant_frequency/:id/edit_comment' => 'assistant_frequency#edit_comment', as: :edit_assistant_frequency_comment
  post 'assistant_frequency/open_period/:semester_id/:month/:last_filter' => 'assistant_frequency#open_frequency_period', as: :open_frequency_period
  post 'assistant_frequency/close_period/:semester_id/:month/:last_filter' => 'assistant_frequency#close_frequency_period', as: :close_frequency_period
  post 'assistant_frequency/request_frequency/' => 'assistant_frequency#request_frequency', as: :request_frequency
  post 'assistant_frequency/mark_generic_assistant_role_frequency/' => 'assistant_frequency#mark_generic_assistant_role_frequency', as: :mark_generic_assistant_role_frequency
  post 'assistant_frequency/mark_assistant_role_frequency/' => 'assistant_frequency#mark_assistant_role_frequency', as: :mark_assistant_role_frequency
  post 'assistant_frequency/:id/comment' => 'assistant_frequency#update_comment', as: :update_assistant_frequency_comment
  post 'assistant_frequency/pay_all_assistants/:semester_id/:month' => 'assistant_frequency#pay_all_assistants', as: :pay_all_assistants

  resources :semesters
  get 'semesters/:id/edit_date' => 'semesters#edit_date', as: :semester_edit_date
  post 'semesters/:id/open' => 'semesters#open', as: :open_semester
  post 'semesters/:id/activate' => 'semesters#activate', as: :activate_semester
  post 'semesters/:id/close' => 'semesters#close', as: :close_semester
  post 'semesters/:id/deactivate' => 'semesters#deactivate', as: :deactivate_semester
  post 'semesters/:id/open_evaluation_period' => 'semesters#open_evaluation_period', as: :open_semester_evaluation_period
  post 'semesters/:id/close_evaluation_period' => 'semesters#close_evaluation_period', as: :close_semester_evaluation_period
  patch 'semesters/:id/update_date' => 'semesters#update_date', as: :semester_update_date

  resources :candidatures, except: :new
  get 'candidatures/:id/download_transcript' => 'candidatures#download_transcript', as: :download_candidature_transcript
  get 'candidatures/:semester_id/new' => 'candidatures#new', as: :new_candidature
  get 'candidatures/list/:department_id/' => 'candidatures#index', as: :candidatures_with_department
  get 'candidatures/for_department/:semester_id/:department_id/' => 'candidatures#index_for_department', as: :candidatures_for_department
  get 'candidatures/for_student/:student_id/' => 'candidatures#index_for_student', as: :candidatures_for_student

  get 'assistant_roles/' => 'assistant_roles#index', as: :assistant_roles
  get 'assistant_roles/edit_date/:id' => 'assistant_roles#edit_date', as: :assistant_roles_edit_date
  get 'assistant_roles/for_semester/:semester_id' => 'assistant_roles#index', as: :assistant_roles_for_semester
  get 'assistant_roles/for_semester/:semester_id/:department_id' => 'assistant_roles#index', as: :assistant_roles_for_semester_and_department
  get 'assistant_roles/for_professor/:professor_id/' => 'assistant_roles#index_for_professor', as: :assistant_roles_for_professor
  get 'assistant_roles/for_professor/:professor_id/:semester_id' => 'assistant_roles#index_for_professor', as: :assistant_roles_for_professor_and_semester
  get 'assistant_roles/certificate/:id' => 'assistant_roles#certificate', as: :certificate
  get 'assistant_roles/report_form/:id' => 'assistant_roles#report_form', as: :report_form
  get 'assistant_roles/print_report/:id' => 'assistant_roles#print_report', as: :print_report
  get 'assistant_roles/:request_for_teaching_assistant_id/new' => 'assistant_roles#new', as: :new_assistant_role
  post 'assistant_roles/notify_for_semester/:semester_id' => 'assistant_roles#notify_for_semester', as: :notify_assistant_roles_for_semester
  post 'assistant_roles/request_evaluations_for_semester/:semester_id' => 'assistant_roles#request_evaluations_for_semester', as: :request_assistant_evaluations_for_semester
  post 'assistant_roles/:request_for_teaching_assistant_id/:student_id/create' => 'assistant_roles#create', as: :create_assistant_role
  post 'assistant_roles/deactivate_assistant_role/:id' => 'assistant_roles#deactivate_assistant_role', as: :deactivate_assistant_role
  post 'assistant_roles/reactivate_assistant_role/:id' => 'assistant_roles#reactivate_assistant_role', as: :reactivate_assistant_role
  patch 'assistant_roles/update_date/:id' => 'assistant_roles#update_date', as: :update_assistant_role_date
  patch 'assistant_roles/:id/' => 'assistant_roles#update', as: :update_assistant_role
  patch 'assistant_roles/make_definitive/:id' => 'assistant_roles#make_definitive', as: :make_assistant_role_definitive
  delete 'assistant_roles/:id/' => 'assistant_roles#destroy', as: :destroy_assistant_role

  resources :assistant_evaluations, except: [:index, :show, :new, :destroy]
  get 'assistant_evaluations/for_student/:student_id/' => 'assistant_evaluations#index_for_student', as: :assistant_evaluations_for_student
  get 'assistant_evaluations/:assistant_role_id/new' => 'assistant_evaluations#new', as: :new_assistant_evaluation

  get "help_students/:id" => "help_students#index", :as => :help_students

  get "help_professors/:id" => "help_professors#index", :as => :help_professors

  match '/403', to: 'errors#access_denied', via: :all
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  devise_scope :user do
    match '/users/auth/USP/callback', to: 'users/omniauth_callbacks#usp', via: [:get, :post]
  end

  get '/_instructions' => redirect('http://www.ime.usp.br/grad/monitoria'), as: :official_instructions

end

app/controllers/candidatures_controller.rb
class CandidaturesController < ApplicationController
  authorize_resource
  before_action :set_candidature, only: [:show, :download_transcript, :edit, :update, :destroy]

  # GET /candidatures
  # GET /candidatures.json
  def index
    if user_signed_in?
      current_user.professor do |professor|
        if professor.super_professor? and not professor.hiper_professor?
          redirect_to candidatures_for_department_path(Semester.current, professor.department)
        end
      end
      current_user.student do |student|
        redirect_to candidatures_for_student_path(student)
      end
    end
    @departments = Department.all
  end

  def index_for_department
    @current_department = Department.find(params[:department_id])
    @semester = Semester.find(params[:semester_id])
    @active_semesters = Semester.all_active
    @candidatures_filtered = []
    checked = {}
    Candidature.courses_num.times do
      @candidatures_filtered.push([])
    end
    Candidature.where(semester: @semester).all.each do |candidature|
      if candidature.semester.active
        candidature.courses.each_with_index do |course, idx|
          if not checked[candidature] and course and course.department == @current_department
            @candidatures_filtered[idx].push(candidature)
            checked[candidature] = true
          end
        end
      end
    end
    @candidatures_filtered.each do |candidaturelist|
      candidaturelist.sort! { |a,b| a.student.name.downcase <=> b.student.name.downcase }
    end
  end

  def index_for_student
    authorization_same_student params[:student_id]
    student = Student.find(params[:student_id])
    @candidatures = Candidature.where(student_id: student.id).order(:semester_id)
    @roles = AssistantRole.where(student_id: student.id, election: AssistantRole.ELECTION_DEFINITIVE).order(:created_at).reverse
    @semesters = Semester.all_open.map do |semester|
      { get: semester, valid: (not already_for_semester?(student.id, semester.id)) }
    end
    @enable_report = Semester.current.evaluation_period
  end

  # GET /candidatures/1
  # GET /candidatures/1.json
  def show
    authorization_student
    begin
      @history_table = build_pretty_history_table(@candidature.student.history_table)
    rescue
      @history_table = ""
    end
  end

  def download_transcript
    download
  end

  # GET /candidatures/2014/new
  def new
    @candidature = Candidature.new
    @semester = Semester.find(params[:semester_id])
    @active_courses = course_options
  end

  # GET /candidatures/1/edit
  def edit
    authorization_student
    @active_courses = course_options
  end

  # POST /candidatures
  # POST /candidatures.json
  def create
    if params[:candidature][:student_id].nil?
      params[:candidature][:student_id] = current_user.student.id
    end
    @candidature = Candidature.new(candidature_params)
    respond_to do |format|
      if already_for_semester? @candidature.student_id, @candidature.semester_id
        @candidature.errors.add(:semester_id, t('errors.models.candidature.toomany'))
        format.html { redirect_to  new_candidature_path(@candidature.semester) }
        format.json { render json: @candidature.errors, status: :unprocessable_entity }
      elsif @candidature.has_repeated_courses
        @candidature.errors.add(:-, t('errors.models.candidature.repeated'))
        format.html { redirect_to new_candidature_path(@candidature.semester)}
        format.json { render json: @candidature.errors, status: :unprocessable_entity }
      elsif @candidature.save
        BackupMailer.new_candidature(@candidature).deliver
        format.html { redirect_to @candidature, notice: 'Candidatura criada com sucesso.' }
        format.json { render action: 'show', status: :created, location: @candidature }
      else
        format.html { redirect_to new_candidature_path(@candidature.semester)}
        format.json { render json: @candidature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidatures/1
  # PATCH/PUT /candidatures/1.json
  def update
    authorization_student
    respond_to do |format|
      if @candidature.update(candidature_params)
        BackupMailer.edit_candidature(@candidature).deliver
        format.html { redirect_to @candidature, notice: 'Candidatura atualizada com sucesso.' }
        format.json { render action: 'show', status: :ok, location: @candidature }
      else
        format.html { render action: 'edit' }
        format.json { render json: @candidature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidatures/1
  # DELETE /candidatures/1.json
  def destroy
    authorization_student
    BackupMailer.delete_candidature(@candidature).deliver
    @candidature.destroy
    respond_to do |format|
      format.html { redirect_to candidatures_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_candidature
    @candidature = Candidature.find(params[:id])
  end

  def authorization_same_student student_id
    if user_signed_in?
      current_user.student do |student|
        raise CanCan::AccessDenied.new() if student_id != student.id.to_s
      end
    end
  end

  def authorization_student
    if user_signed_in?
      current_user.student do |student|
        raise CanCan::AccessDenied.new() if @candidature.student_id != student.id
      end
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def candidature_params
    params.require(:candidature).permit(
      :daytime_availability, :nighttime_availability, :time_period_preference,
      :course1_id, :course2_id, :course3_id, :course4_id, :student_id, :semester_id,
      :observation, :transcript_file_path, :voluntary
    )
  end

  def candidature_of_department?(professor, candidature)
    course1 = Course.where(id: candidature.course1_id).take
    if(course1.department == professor.department)
      return true
    end
    return false
  end

  def already_for_semester? student_id, semester_id
    Candidature.where(student_id: student_id, semester_id: semester_id).any?
  end

  def course_options
    Course.where(status: true).order(:course_code).map do |course|
      [course.course_code + " - " + course.name, course.department.code, course.id]
    end
  end

  def build_pretty_history_table history_json
    history_items = []
    history_json["historico"].each do |item|
      course_code = item["coddis"]
      grade = item["nota"]
      status = item["rstfim"]
      year_semester = item["codtur"][0..4]
      history_item = HistoryItem.new(course_code, grade, status, year_semester)
      history_items.push(history_item)
    end
    history_items.sort
  end

end

app/helpers/candidatures_helper.rb
module CandidaturesHelper

  def daytimePreference
    [
      ["Diurno", 0],
      ["Noturno", 1],
      ["Indiferente", 2]
    ]
  end

  def course_options
    Course.all.order(:course_code).map do |course|
      [course.course_code + " - " + course.name, course.department.code, course.id]
    end
  end

  def student_options
    (Student.all.map do |student|
      [student.name, student.id]
    end).sort
  end
end

app/views/candidatures/edit.html.erb
<h1>Edição de Candidatura</h1>

<%= render 'form' %>

app/views/candidatures/index.html.erb
<h1>Candidaturas por departamento:</h2>

<div class="row" style="height:5em">
  <%= button_link_to "Realizar candidatura em nome de aluno(a)", new_candidature_path(Semester.current) %>
</div>

<div class "row">
  <ul>
  <% @departments.each do |dep| %>
    <li>
      <%= button_link_to dep.code, candidatures_for_department_path(Semester.current, dep) %>
    </li>
  <% end %>
  </ul>
</div>

<% if @current_department %>
  <% dep = @current_department.code %>
  <% unless @candidatures_filtered[dep].empty? %>
    <h1><%= dep.upcase %></h2>
    <% @candidatures_filtered[dep].each do |candidature| %>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>
              <%= t('activerecord.attributes.student.nusp') + ': ' + candidature.student.nusp %>
            </th>
            <th><%= candidature.student.name %></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="title"><%= t('activerecord.attributes.student.institute') %></td>
            <td><%= candidature.student.institute %></td>
          </tr>
          <tr>
            <td class="title"><%= t('activerecord.attributes.candidature.semester_id') %></td>
            <td><%= candidature.semester.period_as_s %></td>
          </tr>
          <tr>
            <td class="title">
              <%= t('activerecord.attributes.candidature.course1_id') %>
            </td>
            <td>
              <% course = Course.find(candidature.course1_id) %>
              <%= course.course_code + " - " + course.name %>
            </td>
          </tr>
          <% if candidature.course2_id != nil %>
            <tr>
              <td class="title">
                <%= t('activerecord.attributes.candidature.course2_id') %>
              </td>
              <td>
                <% course = Course.find(candidature.course2_id) %>
                <%= course.course_code + " - " + course.name %>
              </td>
            </tr>
          <% end %>
          <% if candidature.course3_id != nil %>
            <tr>
              <td class="title">
                <%= t('activerecord.attributes.candidature.course3_id') %>
              </td>
              <td>
                <% course = Course.find(candidature.course3_id) %>
                <%= course.course_code + " - " + course.name %>
              </td>
            </tr>
          <% end %>
          <% if candidature.course4_id != nil %>
            <tr>
              <td class="title">
                <%= t('activerecord.attributes.candidature.course4_id') %>
              </td>
              <td>
                <% course = Course.find(candidature.course4_id) %>
                <%= course.course_code + " - " + course.name %>
              </td>
            </tr>
          <% end %>
          <tr>
            <td colspan="2"><%= button_link_to 'Mais informações', candidature %></th>
          </tr>
        </tbody>
      </table>
      <br>
    <% end %>
  <% end %>
<% end %>

<br>

<% if current_student? %>
  <% @semesters.each do |semester| %>
    <% if semester[:valid] %>
      <%= button_link_to "Candidatar-se para #{semester[:get].year}/#{semester[:get].parity_as_i}",
                  new_candidature_path(semester[:get]) %>
    <% end %>
  <% end %>
<% end %>

app/views/candidatures/index_for_student.html.erb
<h1>Minhas candidaturas</h1>

<% if @candidatures.any? %>
  <% @candidatures.reverse.each do |candidature| %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th colspan="2">
            <%= candidature.semester.period_as_s %>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="title">
            <%= t('activerecord.attributes.candidature.course1_id') %>
          </td>
          <td class="name">
            <% course = Course.find(candidature.course1_id) %>
            <%= course.course_code + " - " + course.name %>
          </td>
        </tr>
        <% if candidature.course2_id != nil %>
          <tr>
            <td class="title">
              <%= t('activerecord.attributes.candidature.course2_id') %>
            </td>
            <td class="name">
              <% course = Course.find(candidature.course2_id) %>
              <%= course.course_code + " - " + course.name %>
            </td>
          </tr>
        <% end %>
        <% if candidature.course3_id != nil %>
          <tr>
            <td class="title">
              <%= t('activerecord.attributes.candidature.course3_id') %>
            </td>
            <td class="name">
              <% course = Course.find(candidature.course3_id) %>
              <%= course.course_code + " - " + course.name %>
            </td>
          </tr>
        <% end %>
        <% if candidature.course4_id != nil %>
          <tr>
            <td class="title">
              <%= t('activerecord.attributes.candidature.course4_id') %>
            </td>
            <td class="name">
              <% course = Course.find(candidature.course4_id) %>
              <%= course.course_code + " - " + course.name %>
            </td>
          </tr>
        <% end %>
        <tr>
          <td colspan="2"><%= button_link_to 'Mais informações', candidature %></td>
        </tr>
      </tbody>
    </table>
    <br>
  <% end %>
<% else %>
  <h2><i>Você não tem nenhuma candidatura</i></h2>
<% end %>

<h1>Minhas monitorias</h1>

<% if @roles.any? %>
  <% @roles.each do |role| %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th colspan="5">
            <%= role.semester.period_as_s %>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="title">
            Curso
          </td>
          <td class="name" colspan="4">
            <%= role.course.full_name %>
          </td>
        </tr>
        <tr>
          <td class="title">
            Professor
          </td>
          <td class="name" colspan="4">
            <%= role.professor.name %>
          </td>
        </tr>
        <tr>
          <% if role.active %>
            <td class="title">
              Presenças marcadas
            </td>
            <% role.request_for_teaching_assistant.semester.months.each do |month| %>
              <td>
                <%= month_name month %>:
                <% status = role.frequency_status_for_month(month) %>
                <% if status == "Presente" %>
                  <% style = "text-success" %>
                <% elsif status == "Pendente" %>
                  <% style = "text-warning" %>
                <% elsif status == "Ausente" %>
                  <% style = "text-danger" %>
                <% else %>
                  <% style = "text-muted" %>
                <% end %>
                <strong class="<%= style %>">
                  <%= status %>
                </strong>
              </td>
            <% end %>
          <% else %>
            <td colspan="5" class="text-center">
              <strong>DESATIVADO(A)</strong>
            </td>
          <% end %>
        </tr>
        <% if (role.report_filled?) %>
          <tr>
            <td colspan="5"><%= button_link_to 'Ver relatório', print_report_path(role.id, :format => :pdf), target: "_blank" %></td>
          </tr>
        <% elsif role.semester.evaluation_period %>
          <tr>
            <td colspan="5"><%= button_link_to 'Preencher relatório', report_form_path(role.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
  <% end %>
<% else %>
  <h2><i>Você não tem nenhuma monitoria</i></h2>
<% end %>


<br>

<% if current_student? %>
  <% @semesters.each do |semester| %>
    <% if semester[:valid] %>
      <%= button_link_to "Candidatar-se para #{semester[:get].as_s}",
                  new_candidature_path(semester[:get]) %>
    <% end %>
  <% end %>
<% end %>

app/views/candidatures/new.html.erb
<h1>Nova Candidatura</h1>

<%= render 'form' %>

app/views/candidatures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('activerecord.attributes.student.student') + ':' %></strong>
  <%= @candidature.student.name %>
</p>

<p>
  <strong><%= t('activerecord.attributes.student.nusp') + ':' %></strong>
  <%= @candidature.student.nusp %>
</p>

<p>
  <strong><%= t('activerecord.attributes.student.email') + ':' %></strong>
  <%= @candidature.student.email %>
</p>

<!-- AMAGAD GAMBZ -->
<!-- fomos incapazes de fazer o render template do students/_show funcionar, então... -->

<h2>Dados de aluno</h2>

<p>
  <strong><%= t('activerecord.attributes.student.gender') + ':' %></strong>
  <% if (@candidature.student.gender == 0) %>
    <%="Feminino"%>
  <%else%>
    <%="Masculino"%>
  <%end%>
</p>

<p>
  <strong><%= t('activerecord.attributes.student.institute') + ':' %></strong>
  <% if @candidature.student.institute != "Outros" %>
    <%= @candidature.student.institute %>
  <% else %>
    <%= @candidature.student.institute_text %>
  <% end %>
</p>

<p>
  <strong><%= t('activerecord.attributes.student.rg') + ':' %></strong>
  <%= @candidature.student.rg %>
</p>

<p>
  <strong><%= t('activerecord.attributes.student.cpf') + ':' %></strong>
  <%= @candidature.student.cpf %>
</p>

<p>
  <strong><%= t('activerecord.attributes.student.address') + ':' %></strong>
 	<%= @candidature.student.address %>
</p>

<p>
  <strong><%= t('activerecord.attributes.student.complement') + ':' %></strong>
  <%= @candidature.student.complement %>
</p>

<p>
  <strong><%= t('activerecord.attributes.student.district') + ':' %></strong>
  <%= @candidature.student.district %>
</p>
<p>
  <strong><%= t('activerecord.attributes.student.cep') + ':' %></strong>
  <%= @candidature.student.zipcode %>
</p>

<p>
  <strong><%= t('activerecord.attributes.student.city') + ':' %></strong>
  <%= @candidature.student.city %>
</p>
<p>
  <strong><%= t('activerecord.attributes.student.state') + ':' %></strong>
  <%= @candidature.student.state %>
</p>
<p>
  <strong><%= t('activerecord.attributes.student.tel') + ':' %></strong>
  <%= @candidature.student.tel %>
</p>
<p>
  <strong><%= t('activerecord.attributes.student.cel') + ':' %></strong>
  <%= @candidature.student.cel %>
</p>

<% if current_super_professor? or admin_signed_in? or secretary_signed_in? %>
  <%= button_link_to 'Ver avaliações como monitor(a)', assistant_evaluations_for_student_path(@candidature.student) %>
<% end %>
<span style="height: 2em; display: block;"></span>

<% if !(current_student?)%>
  <h2> Histórico escolar </h2>
  <% if @history_table == "" %>
  <div class="biggerText">
    <p class="text-danger">
      Não foi possível acessar o histórico do estudante nos sistemas USP.
    </p>
    <p class="text-danger">
      Por favor, consulte diretamente o Júpiter ou o Janus.
    </p>
  </div>
  <% else %>
  <div class="biggerText">
    Obs.: O histórico apresenta apenas a última vez que o aluno
    cursou cada disciplina. Reprovações de matérias que foram
    cursadas novamente não aparecem. Caso necessário,
    consulte o Júpiter para o histórico completo.
  </div>
    <% curr_year_semester = "" %>
    <% @history_table.each do |item| %>
    <% if (curr_year_semester != item.year_semester) %>
      <% if (curr_year_semester != "") %>
        </tbody>
        </table>
      <% end %>
      <% curr_year_semester = item.year_semester %>
      <h3><%= item.semester %>º semestre de <%= item.year %></h3>
      <table class="table table-hover">
        <thead>
          <th>Curso</th>
          <th>Nota</th>
          <th>Status</th>
        </thead>
        <tbody>
          <% end %>
            <tr>
              <td><%= item.course_name %></td>
              <td><%= item.grade %></td>
              <td><%= item.full_status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
  <% end %>

  <span style="height: 2em; display: block;"></span>
<% end %>

<h2>Dados da candidatura</h2>

<p>
  <strong><%= t('activerecord.attributes.candidature.semester') + ':' %></strong>
  <%= @candidature.semester.as_s %>
</p>

<p>
  <strong><%= t('activerecord.attributes.candidature.course1_id') + ':' %></strong>
  <% course = Course.find(@candidature.course1_id) %>
  <%= course.course_code + " - " + course.name %>
</p>

<p>
  <strong><%= t('activerecord.attributes.candidature.course2_id') + ':' %></strong>
  <% if @candidature.course2_id != nil%>
    <% course = Course.find(@candidature.course2_id) %>
    <%= course.course_code + " - " + course.name %>
  <% else %>
    <i>Nenhum</i>
  <% end %>
</p>

<p>
  <strong><%= t('activerecord.attributes.candidature.course3_id') + ':' %></strong>
  <% if @candidature.course3_id != nil%>
    <% course = Course.find(@candidature.course3_id) %>
    <%= course.course_code + " - " + course.name %>
  <% else %>
    <i>Nenhum</i>
  <% end %>
</p>

<p>
  <strong><%= t('activerecord.attributes.candidature.course4_id') + ':' %></strong>
  <% if @candidature.course4_id != nil%>
    <% course = Course.find(@candidature.course4_id) %>
    <%= course.course_code + " - " + course.name %>
  <% else %>
    <i>Nenhum</i>
  <% end %>
</p>

<p>
  <strong><%= t('activerecord.attributes.candidature.daytime_availability') + ':' %></strong>
  <%= show_yes_or_no(@candidature.daytime_availability) %>
</p>

<p>
  <strong><%= t('activerecord.attributes.candidature.nighttime_availability') + ':' %></strong>
  <%= show_yes_or_no(@candidature.nighttime_availability) %>
</p>

<p>
  <strong><%= t('activerecord.attributes.candidature.time_period_preference') + ':' %></strong>
  <%= daytimePreference()[@candidature.time_period_preference.to_i][0] %>
</p>

<p>
  <strong><%= t('activerecord.attributes.candidature.voluntary') + ':' %></strong>
  <%= show_yes_or_no(@candidature.voluntary) %>
</p>

<p>
  <strong><%= t('activerecord.attributes.candidature.observation') + ':' %></strong>
  <%= (@candidature.observation) %>
</p>

<% if current_student? or secretary_signed_in? %>
  <% if @candidature.semester.open %>
    <%= button_link_to 'Editar', edit_candidature_path(@candidature) %>
    <%= button_link_to 'Remover', @candidature, method: :delete, data: { confirm: 'Tem certeza?' } %>
  <% end %>
<% end %>