config/routes.rb
Rails.application.routes.draw do

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  get 'errors/access_denied'

  get 'home/index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins, :controllers => { :admins => "admins" }
  devise_for :secretaries, :controllers => { :secretaries => "secretaries" }

  root 'home#index'
  get '/sistema' => 'home#sys'
  get '/prof' => 'home#index'
  get '/about' => 'home#about', as: :about
  get '/professors/sign_in/' => 'home#index'
  get "/users/sign_in/" => "home#index"

  resources :users, except: :edit

  resources :admins do
    collection do
      get :control_panel
      post :duplicate_students
      post :register_undergraduate_courses
      post :register_postgraduate_courses
    end
  end

  resources :advises
  post 'advises/:id/moveup' => 'advises#moveup', as: :moveup_advise
  post 'advises/:id/movedown' => 'advises#movedown', as: :movedown_advise

  resources :request_for_teaching_assistants, except: [:new]
  get 'request_for_teaching_assistants/:semester_id/new' => 'request_for_teaching_assistants#new', as: :new_request_for_teaching_assistant
  get 'request_for_teaching_assistants_for_semester/:semester_id/' => 'request_for_teaching_assistants#index_for_semester', as: :request_for_teaching_assistants_for_semester
  get 'request_for_teaching_assistants_for_professor/:professor_id/' => 'request_for_teaching_assistants#index_for_professor', as: :request_for_teaching_assistants_for_professor
  get 'request_for_teaching_assistants_for_professor_and_semester/:professor_id/:semester_id/' => 'request_for_teaching_assistants#index_for_professor', as: :request_for_teaching_assistants_for_professor_and_semester

  resources :professors
  get 'professors/:id/change_password' => 'professors#change_password', as: :change_professor_password
  post 'professors/:id/make_superprofessor' => 'professors#make_superprofessor', as: :make_super_professor

  resources :courses

  resources :secretaries
  get 'secretaries/:id/change_password' => 'secretaries#change_password', as: :change_secretary_password

  resources :students, except: :show

  resources :assistant_frequency do
    collection do
      get :index
      post :request_frequency
    end
  end

  get 'dumps/' => 'dumps#index', as: :dumps

  get 'assistant_frequency/monthly_control/:semester_id/:month/:filter' => 'assistant_frequency#monthly_control', as: :assistant_frequency_monthly_control
  get 'assistant_frequency/monthly_control/:semester_id/:month/:department_id/:filter' => 'assistant_frequency#monthly_control', as: :assistant_frequency_monthly_control_for_department
  get 'assistant_frequency/:id/edit_comment' => 'assistant_frequency#edit_comment', as: :edit_assistant_frequency_comment
  post 'assistant_frequency/open_period/:semester_id/:month/:last_filter' => 'assistant_frequency#open_frequency_period', as: :open_frequency_period
  post 'assistant_frequency/close_period/:semester_id/:month/:last_filter' => 'assistant_frequency#close_frequency_period', as: :close_frequency_period
  post 'assistant_frequency/request_frequency/' => 'assistant_frequency#request_frequency', as: :request_frequency
  post 'assistant_frequency/mark_generic_assistant_role_frequency/' => 'assistant_frequency#mark_generic_assistant_role_frequency', as: :mark_generic_assistant_role_frequency
  post 'assistant_frequency/mark_assistant_role_frequency/' => 'assistant_frequency#mark_assistant_role_frequency', as: :mark_assistant_role_frequency
  post 'assistant_frequency/:id/comment' => 'assistant_frequency#update_comment', as: :update_assistant_frequency_comment
  post 'assistant_frequency/pay_all_assistants/:semester_id/:month' => 'assistant_frequency#pay_all_assistants', as: :pay_all_assistants

  resources :semesters
  get 'semesters/:id/edit_date' => 'semesters#edit_date', as: :semester_edit_date
  post 'semesters/:id/open' => 'semesters#open', as: :open_semester
  post 'semesters/:id/activate' => 'semesters#activate', as: :activate_semester
  post 'semesters/:id/close' => 'semesters#close', as: :close_semester
  post 'semesters/:id/deactivate' => 'semesters#deactivate', as: :deactivate_semester
  post 'semesters/:id/open_evaluation_period' => 'semesters#open_evaluation_period', as: :open_semester_evaluation_period
  post 'semesters/:id/close_evaluation_period' => 'semesters#close_evaluation_period', as: :close_semester_evaluation_period
  patch 'semesters/:id/update_date' => 'semesters#update_date', as: :semester_update_date

  resources :candidatures, except: :new
  get 'candidatures/:id/download_transcript' => 'candidatures#download_transcript', as: :download_candidature_transcript
  get 'candidatures/:semester_id/new' => 'candidatures#new', as: :new_candidature
  get 'candidatures/list/:department_id/' => 'candidatures#index', as: :candidatures_with_department
  get 'candidatures/for_department/:semester_id/:department_id/' => 'candidatures#index_for_department', as: :candidatures_for_department
  get 'candidatures/for_student/:student_id/' => 'candidatures#index_for_student', as: :candidatures_for_student

  get 'assistant_roles/' => 'assistant_roles#index', as: :assistant_roles
  get 'assistant_roles/edit_date/:id' => 'assistant_roles#edit_date', as: :assistant_roles_edit_date
  get 'assistant_roles/for_semester/:semester_id' => 'assistant_roles#index', as: :assistant_roles_for_semester
  get 'assistant_roles/for_semester/:semester_id/:department_id' => 'assistant_roles#index', as: :assistant_roles_for_semester_and_department
  get 'assistant_roles/for_professor/:professor_id/' => 'assistant_roles#index_for_professor', as: :assistant_roles_for_professor
  get 'assistant_roles/for_professor/:professor_id/:semester_id' => 'assistant_roles#index_for_professor', as: :assistant_roles_for_professor_and_semester
  get 'assistant_roles/certificate/:id' => 'assistant_roles#certificate', as: :certificate
  get 'assistant_roles/report_form/:id' => 'assistant_roles#report_form', as: :report_form
  get 'assistant_roles/print_report/:id' => 'assistant_roles#print_report', as: :print_report
  get 'assistant_roles/:request_for_teaching_assistant_id/new' => 'assistant_roles#new', as: :new_assistant_role
  post 'assistant_roles/notify_for_semester/:semester_id' => 'assistant_roles#notify_for_semester', as: :notify_assistant_roles_for_semester
  post 'assistant_roles/request_evaluations_for_semester/:semester_id' => 'assistant_roles#request_evaluations_for_semester', as: :request_assistant_evaluations_for_semester
  post 'assistant_roles/:request_for_teaching_assistant_id/:student_id/create' => 'assistant_roles#create', as: :create_assistant_role
  post 'assistant_roles/deactivate_assistant_role/:id' => 'assistant_roles#deactivate_assistant_role', as: :deactivate_assistant_role
  post 'assistant_roles/reactivate_assistant_role/:id' => 'assistant_roles#reactivate_assistant_role', as: :reactivate_assistant_role
  patch 'assistant_roles/update_date/:id' => 'assistant_roles#update_date', as: :update_assistant_role_date
  patch 'assistant_roles/:id/' => 'assistant_roles#update', as: :update_assistant_role
  patch 'assistant_roles/make_definitive/:id' => 'assistant_roles#make_definitive', as: :make_assistant_role_definitive
  delete 'assistant_roles/:id/' => 'assistant_roles#destroy', as: :destroy_assistant_role

  resources :assistant_evaluations, except: [:index, :show, :new, :destroy]
  get 'assistant_evaluations/for_student/:student_id/' => 'assistant_evaluations#index_for_student', as: :assistant_evaluations_for_student
  get 'assistant_evaluations/:assistant_role_id/new' => 'assistant_evaluations#new', as: :new_assistant_evaluation

  get "help_students/:id" => "help_students#index", :as => :help_students

  get "help_professors/:id" => "help_professors#index", :as => :help_professors

  match '/403', to: 'errors#access_denied', via: :all
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  devise_scope :user do
    match '/users/auth/USP/callback', to: 'users/omniauth_callbacks#usp', via: [:get, :post]
  end

  get '/_instructions' => redirect('http://www.ime.usp.br/grad/monitoria'), as: :official_instructions

end

app/models/assistant_role.rb
class AssistantRole < ActiveRecord::Base
  include ActiveModel::Validations
  validates :student_id, presence: true
  validates :request_for_teaching_assistant_id, presence: true
  validates :election, presence: true
  belongs_to :student
  belongs_to :request_for_teaching_assistant
  has_one :assistant_evaluation
  has_many :assistant_frequency

  def self.ELECTION_UNCERTAIN
    0
  end

  def self.ELECTION_DEFINITIVE
    1
  end

  def uncertain?
    election == AssistantRole.ELECTION_UNCERTAIN
  end

  def definitive?
    election == AssistantRole.ELECTION_DEFINITIVE
  end

  def make_definitive
    update_column(:election, AssistantRole.ELECTION_DEFINITIVE)
  end

  def semester
    request_for_teaching_assistant.semester
  end

  def professor
    request_for_teaching_assistant.professor
  end

  def course
    request_for_teaching_assistant.course
  end

  def deactivate
    update_column(:active, false)
  end

  def reactivate
    update_column(:active, true)
  end

  def update_date_start_end(started_date, finished_date)
    update_column(:started_at, :started_date)
    update_column(:finished_at, :finished_date)
  end

  def report_filled?
    !(report_creation_date.nil?)
  end

  def frequency_for_month month
    assistant_frequency.where(month: month).take
  end

  def standard_first_day
    DateTime.new(semester.year, semester.months[0], 1)
  end

  def month_presence month
    first = DateTime.new(semester.year, month, 1)
    last = DateTime.new(semester.year, month, -1)
    if started_at > first and started_at < last then
      100*((last - started_at.to_datetime)/(last - first)).to_f
    else
      nil
    end
  end

  def self.for_semester semester
    (where request_for_teaching_assistant: (RequestForTeachingAssistant.where semester: semester)).sort do |role1, role2|
      role1.student.name <=> role2.student.name
    end
  end

  def self.for_professor_and_semester professor, semester
    (where request_for_teaching_assistant: (RequestForTeachingAssistant.where professor: professor, semester: semester), election: self.ELECTION_DEFINITIVE).sort do |role1, role2|
      role1.student.name <=> role2.student.name
    end
  end

  def self.for_department_and_semester department, semester
    (where request_for_teaching_assistant: (RequestForTeachingAssistant.where semester: semester, course: (Course.where department: department))).sort do |role1, role2|
      role1.student.name <=> role2.student.name
    end
  end

  def self.all_current
    semester = Semester.current
    requests = RequestForTeachingAssistant.where(semester: semester)
    first_day = DateTime.new(DateTime.now.year, 1, 1)
    last_day = DateTime.new(DateTime.now.year, 12, 31)
    AssistantRole.where(request_for_teaching_assistant: requests, active: true, started_at: first_day..DateTime.now, finished_at: DateTime.now..last_day)
  end

  def self.pending_for_month month
    all_current.select do |role|
      AssistantFrequency.where(month: month, assistant_role: role).empty?
    end
  end

  def frequency_status_for_month month
    found = false
    assistant_frequency.each do |freq|
      if month == freq.month
        found = true
        if freq.presence
          if freq.payment
            return "Pago"
          end
          return "Presente"
        else
          return "Ausente"
        end
      end
    end
    if !found
      if active and semester.frequency_open?(Semester.month_to_period month)
        if self.started_at.mon > month || self.finished_at.mon < month
          return "---"
        end
        return "Pendente"
      else
        if self.started_at.mon > month || self.finished_at.mon < month
          return "---"
        end
        return "Pendente"
      end
    end
  end

  def frequency_status_for_period period
    found = false
    assistant_frequency.each do |freq|
      if freq.semester.months[period] == freq.month
        found = true
        if freq.presence
          if freq.payment
            return "Pago"
          end
          return "Presente"
        else
          return "Ausente"
        end
      end
    end
    if !found
      if active and semester.frequency_open?(period)
        if Semester.month_to_period(self.started_at.mon) > period ||
              Semester.month_to_period(self.finished_at.mon) < period
          return "---"
        end
        return "Pendente"
      else
        if Semester.month_to_period(self.started_at.mon) > period ||
              Semester.month_to_period(self.finished_at.mon) < period
          return "---"
        end
        return "Pendente"
      end
    end
  end

  def frequency_status_for_month_as_number month
    found = false
    assistant_frequency.each do |freq|
      if month == freq.month
        found = true
        if freq.presence
          return 3
        else
          return 1
        end
      end
    end
    if !found
      return 2
    end
  end

end

app/helpers/assistant_roles_helper.rb
module AssistantRolesHelper
  def months_to_names
    [
      '',
      'Janeiro',
      'Fevereiro',
      'Março',
      'Abril',
      'Maio',
      'Junho',
      'Julho',
      'Agosto',
      'Setembro',
      'Outubro',
      'Novembro',
      'Dezembro'
    ]
  end
  def workloads
    [
      ["Pesado", 0],
      ["Razoável", 1],
      ["Leve", 2]
    ]
  end
end

app/views/assistant_roles/_candidates.html.erb
<% if !title.nil? and !title.empty? %>
<h4><%= title %></h4>
<% end %>

<% if candidates.any? %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Nº USP</th>
        <th>Já foi eleito?</th>
        <th colspan=\"2\"></th>
      </tr>
    </thead>
    <tbody>
      <% candidates.each do |candidature| %>
        <% if candidature.elected? %>
          <tr class="elected">
        <% else %>
          <tr>
        <% end %>
        <td><%= candidature.student.name %></td>
        <td><%= candidature.student.nusp.to_s %></td>
        <td><%= show_yes_or_no(candidature.elected?) %></td>
        <td><%= link_to('Detalhes', candidature, class: "btn btn-primary") %></td>
        <% if candidature.elected? %>
          <td><%= button_link_to('Eleger', create_assistant_role_path(@request, candidature.student, class: "btn btn-primary"),
          method: :post, data: {confirm: "Este estudante já foi eleito para monitor(a) de outra disciplina, está certo que deseja elegê-lo(a) novamente?"}) %></td>
        <% else %>
          <td><%= button_link_to('Eleger', create_assistant_role_path(@request, candidature.student), method: :post, class: "btn btn-primary") %></td>
        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p><i>Nenhum candidato nesta categoria</i></p>
<% end %>

app/views/assistant_roles/edit_date.html.erb
<div class="panel-heading text-center" style='font-weight: bold'>
Dados de usuário
</div>

<div class="panel-body">
  <%= form_for @assistant, url: update_assistant_role_date_path(@assistant) do |f| %>
      <div class="form-group">
        <label class="control-label col-sm-4" for="name">
          <%= t('activerecord.attributes.user.name') + ':' %>
        </label>
        <div class="col-sm-8">
          <p class="form-control-static"><%= @assistant.student.name %></p>
        </div>
      </div>

      <div class="form-group">
        <label class="control-label col-sm-4" for="nusp">
          <%= t('activerecord.attributes.user.nusp') + ':' %>
        </label>
        <div class="col-sm-8">
          <p class="form-control-static"><%= @assistant.student.nusp %></p>
        </div>
      </div>

      <div class="form-group">
        <label class="control-label col-sm-4" for="curso">
          <%= t('activerecord.attributes.course.name') + ':' %>
        </label>
        <div class="col-sm-8">
          <p class="form-control-static"><%= @assistant.course.course_code + ' - ' + @assistant.course.name %></p>
        </div>
      </div>

      <div class="form-group">
        <label class="control-label col-sm-4" for="Professor">
          Nome do Professor:
          <!--%= t('activerecord.attributes.professor.name') + ':' %-->
        </label>
        <div class="col-sm-8">
          <p class="form-control-static">
            <%= @assistant.professor.name %>
          </p>
        </div>
      </div>

      <div class="form-group">
        <label class="control-label col-sm-4" for="">
          Data de início:
        </label>
        <div class="col-sm-8">
          <%= f.date_field :started_at %> 
        </div>
      </div>

      <div class="form-group">
        <label class="control-label col-sm-4" for="">
          Data de término:
        </label>
        <div class="col-sm-8">
          <%= f.date_field :finished_at %> 
        </div>
      </div>

      <div class="actions">
        <%= f.submit "Salvar" %>
      </div>
  <% end %>
</div>

app/views/assistant_roles/index.html.erb
<h1>Monitores eleitos para <%= @semester.as_s %></h1>

<div class="row" style="height:1em;"></div>

<div class="row">
  <!-- Seletor de semestres -->
  <div class="col-sm-3">
    <div class="dropdown">
      <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
        <%= @semester.as_s %>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <% Semester.all.order(created_at: :desc).each do |semester| %>
          <li><%= link_to semester.as_s, assistant_roles_for_semester_path(semester)%></li>
        <% end %>
      </ul>
    </div>
  </div>

  <!-- Seletor de departamento -->
  <% if (secretary_signed_in? or current_hiper_professor?) %>
    <div class="col-sm-1">
      <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
          <% if @department.nil? %>
            Todos
          <% else %>
            <%= @department.code %>
          <% end %>
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li>
            <%= link_to "Todos", assistant_roles_for_semester_path(@semester) %>
          </li>
          <% Department.all.order(code: :desc).each do |department| %>
            <li><%= link_to department.code, assistant_roles_for_semester_and_department_path(@semester, department)%></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <% if secretary_signed_in? and @semester.current? %>
    <div class="col-sm-2">
      <%= button_link_to "Notificar monitores", notify_assistant_roles_for_semester_path(@semester), method: :post %>
    </div>
    <div class="col-sm-2">
      <% unless Rails.env.production? %>
        <%= button_link_to "Pedir avaliações dos professores", request_assistant_evaluations_for_semester_path(@semester), method: :post %>
      <% end %>
    </div>
  <% else %>
    <div class="col-sm-10"></div>
  <% end %>
</div>

<div class="row" style="height:1em;"></div>

<table id="roles_table" class="table table-hover">
  <thead>
    <tr>
      <th>Aluno(a)</th>
      <th>Disciplina</th>
      <th>Professor(a)</th>
      <th>Início</th>
      <th>Fim</th>
      <th>Estado</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @assistant_roles.each do |role| %>
      <tr>
        <td>
    			<% if role.student.name != nil %>
            <%=  role.student.name %>
    			<% else %> Nil <% end %>
		    </td>
        <td><%= role.course.course_code %></td>
        <td><%= role.professor.name %></td>

        <!-- Data de inicio -->
        <td>
    			<% if not role.started_at.nil? %>
    				<%= role.started_at.strftime("%d/%m/%Y") %>
    			<% else %>
  				  Indeterminado
  			   <% end %>
  		  </td>

        <!-- Data de fim -->
        <td>
          <% if role.finished_at? %>
            <%= role.finished_at.strftime("%d/%m/%Y") %>
          <% else %>
            Indeterminado
          <% end %>
        </td>

        <!-- Estado -->
        <td>
          <% if role.uncertain? %>
            Não definitivo
          <% elsif role.active? %>
            Ativo(a)
          <% else %>
            Inativo(a)
          <% end %>
        </td>

        <!--  Menu de ações -->
        <td>
          <% if secretary_signed_in? or current_super_professor? %>

            <div class="dropdown">
              <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                <span class="caret"></span>
              </button>

              <!-- Ativar/desativar monitor -->
              <ul class="dropdown-menu">
                <!-- Relatório -->
                <% if role.report_filled? %>
                  <li>
                    <%= link_to 'Ver relatório', print_report_path(role.id, :format => :pdf), target: "_blank" %>
                  </li>
                <% end %>

                <% if secretary_signed_in? %>
                  <%if role.uncertain? %>
                    <li>
                      <%= link_to "Efetivar", make_assistant_role_definitive_path(role), method: :patch, data: { confirm: 'Deseja mesmo tornar esse monitor ou monitora definitivamente eleito? Essa informação ficará acessível a eles!'} %>
                    </li>
                  <% end %>
                  <!-- Ativar/desativar (obsoleto) -->
                  <%if role.active %>
                    <li>
                      <%= link_to "Desativar", deactivate_assistant_role_path(role.id), method: :post, data: { confirm: 'Deseja mesmo desativar este monitor?' } %>
                    </li>
                  <% else %>
                    <li>
                      <%= link_to "Reativar", reactivate_assistant_role_path(role.id), method: :post, data: { confirm: 'Deseja mesmo reativar este monitor?' } %>
                    </li>
                  <% end %>
                  <!-- Gerar atestado -->
                  <li>
                    <%= link_to "Atestado", certificate_path(role.id, :format => :pdf), method: :get, target: "_blank" %>
                  </li>
                  <!-- Editar periodo de monitoria -->
                  <li>
                    <%= link_to "Editar período", assistant_roles_edit_date_path(role) %>
                  </li>
                  <!-- Remover monitor -->
                  <li>
                    <%= link_to "Remover", destroy_assistant_role_path(role), method: :delete, data: { confirm: 'Deseja mesmo remover PERMANENTEMENTE esse monitor?'} %>
                  </li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/assistant_roles/index_for_professor.html.erb
<h1>Meus monitores</h1>

<% if flash[:notice] %>
  <div class="alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end -%>

<div class="row">
  <div class="col-sm-4">
    <div class="dropdown">
      <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
        <%= @semester.as_s %>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <% Semester.all.reverse.each do |semester| %>
          <li><%= link_to semester.as_s, assistant_roles_for_professor_and_semester_path(@professor, semester)%></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="col-sm-8"></div>
</div>

<div class="row" style="height:1em;"></div>

<ul class="list-group">
  <% @assistant_roles.each do |role| %>
    <li class="list-group-item">
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-4">
            <h4 class="list-group-item-heading">
              <%= link_to role.student.name, role.student.user %>
            </h4>
            <p class="list-group-item-text">
              <% if role.student.is_male? %>
                Monitor de <%= role.request_for_teaching_assistant.course.course_code %>
              <% else %>
                Monitora de <%= role.request_for_teaching_assistant.course.course_code %>
              <% end %>
            </p>
          </div>
          <div class="col-sm-8">
            <% if role.active %>
              <div class="row">
                <% @semester.months.each do |month| %>
                  <div class="col-sm-3 text-center">
                    <div class="row">
                      <%= "#{months_to_names[month]}" %>:
                    </div>
                    <div class="row">
                      <% status = role.frequency_status_for_month(month) %>
                      <% color = "black" %>
                      <% if status == "Pendente" and role.semester.frequency_open?Semester.month_to_period(month) %>
                        
                        <div class="col-sm-12 col-lg-6 text-center">
                          <%= button_to "Presente", { controller: "assistant_frequency", action: "mark_assistant_role_frequency", role: role.id, month: month, presence: true, pid: role.professor.id}, method: :post, class: "btn btn-primary btn-xs", data: { confirm: 'Deseja mesmo marcar presença para este monitor?' } %>
                        </div>
                        <div class="col-sm-12 col-lg-6 text-center">
                          <%= button_to "Ausente", { controller: "assistant_frequency", action: "mark_assistant_role_frequency", role: role.id, month: month, presence: false, pid: role.professor.id}, method: :post, class: "btn btn-primary btn-xs", data: { confirm: 'Deseja mesmo marcar ausência para este monitor?' }  %>
                        </div>
                      <% else %>
                        <% if status == "Presente"
                              color = "green"
                           elsif status == "Ausente"
                              color = "red"
                           elsif status == "Pendente"
                              color = "gray"
                            elsif status == "Pago"
                              color = "blue"
                            elsif status == "---"
                              color = "darkgoldenrod"
                           else
                              color = "fucsia"
                           end
                        %>
                        <div class="row">
                          <%= content_tag :span, style: "color:#{color};" do -%>
                            <%= status %>
                          <% end -%>
                          <% if status != "Pendente" && status != "---" %>
                            <%= link_to edit_assistant_frequency_comment_path(role.frequency_for_month(month)), "data-toggle" => "tooltip", title: "Fazer observação" do %>
                                <span class="glyphicon glyphicon-comment"></span>
                            <% end %>
                          <% end %>
                        </div>
                        <div class="row">
                          <% if status != "Pendente" && status != "---" %>
                            <%= role.frequency_for_month(month).comment %>
                          <% end %>
                        </div>
                      <% end %>
                      </div>
                  </div>
                <% end %>
              </div>
            <% else %>
              <p class="text-center">Desativado</p>
            <% end %>
          </div>
        </div>
        <div style="height:1em;"></div>
        <div class="row text-center">
          <% if @semester.evaluation_period %>
            <% if role.assistant_evaluation %>
              <%= button_link_to "Mudar avaliação", edit_assistant_evaluation_path(role.assistant_evaluation) %>
            <% else %>
              <%= button_link_to "Avaliar", new_assistant_evaluation_path(role) %>
            <% end %>
          <% elsif role.assistant_evaluation %>
            <%= button_link_to "Ver avaliações", assistant_evaluations_for_student_path(role.student) %>
          <% else %>
            <%= button_link_to "Avaliar", "#", class: "btn btn-info disabled"%>
          <% end %>
          <% if role.report_filled? %>
            <%= button_link_to "Imprimir relatório", print_report_path(role.id, :format => :pdf), target: "_blank" %>
          <% else %>
            <%= button_link_to "Imprimir relatório", "#", class: "btn btn-info disabled"%>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/assistant_roles/report_form.html.erb
<h1>Relatório de monitoria</h1>

<%= render 'report_form' %>